repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2 # Use the latest Ruff version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest version
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: true # Run pytest on changed files
      - id: kernel-analyzer
        name: kernel-analyzer
        entry: python contrib/kernel_analyzer/kernel_analyzer/cli.py
        args: [mujoco_warp/_src/*.py]
        language: system
        types: [python]
        pass_filenames: false